export interface TerminalLine {
  text: string;
  delay?: number;
  instant?: boolean;
}

export interface TerminalTab {
  name: string;
  lines: TerminalLine[];
}

export const terminalTabs: TerminalTab[] = [
  {
    name: "Quick Start",
    lines: [
      { text: "curl -O https://raw.githubusercontent.com/TraceMachina/nativelink/v1.0.0/nativelink-config/examples/basic_cas.json5", delay: 0, instant: true },
      { text: "  % Total    % Received  Time", delay: 200, instant: true },
      { text: "100  2841  100  2841    0:00:01", delay: 50, instant: true },
      { text: "", delay: 300 },
      { text: "docker run -v $(pwd)/basic_cas.json:/config -p 50051:50051 ghcr.io/tracemachina/nativelink:v1.0.0 config", delay: 200, instant: true },
      { text: "", delay: 400 },
      { text: "Unable to find image locally", delay: 200, instant: true },
      { text: "v1.0.0: Pulling from tracemachina/nativelink", delay: 100, instant: true },
      { text: "a1d0c7532777: Downloading [=>              ] 15%", delay: 120, instant: true },
      { text: "a1d0c7532777: Downloading [=======>        ] 45%", delay: 120, instant: true },
      { text: "a1d0c7532777: Downloading [==============> ] 75%", delay: 120, instant: true },
      { text: "a1d0c7532777: Downloading [================] 100%", delay: 120, instant: true },
      { text: "a1d0c7532777: Pull complete", delay: 200, instant: true },
      { text: "7f9a694b6f8c: Downloading [====>           ] 25%", delay: 120, instant: true },
      { text: "7f9a694b6f8c: Downloading [=========>      ] 60%", delay: 120, instant: true },
      { text: "7f9a694b6f8c: Downloading [==============> ] 90%", delay: 120, instant: true },
      { text: "7f9a694b6f8c: Downloading [================] 100%", delay: 120, instant: true },
      { text: "7f9a694b6f8c: Pull complete", delay: 200, instant: true },
      { text: "Status: Downloaded newer image", delay: 200, instant: true },
      { text: "", delay: 400 },
      { text: "INFO nativelink::config: Loading config from /config", delay: 200, instant: true },
      { text: "INFO nativelink::cas_server: CAS server listening on 0.0.0.0:50051", delay: 150, instant: true },
      { text: "INFO nativelink::scheduler: Scheduler initialized", delay: 150, instant: true },
      { text: "✓ NativeLink ready to serve builds", delay: 300, instant: true },
    ],
  },
  {
    name: "AI Development",
    lines: [
      { text: "> Add retry logic to storage layer", delay: 0, instant: true },
      { text: "", delay: 400 },
      { text: "Using /nativelink-rust-change...", delay: 300, instant: true },
      { text: "", delay: 300 },
      { text: "STATUS:Generating.. (2s · ↑ 420 tokens · thought for 1s)", delay: 150, instant: true },
      { text: "STATUS:Generating.. (4s · ↑ 980 tokens · thought for 2s)", delay: 150, instant: true },
      { text: "STATUS:Generating.. (6s · ↑ 1.5k tokens · thought for 3s)", delay: 150, instant: true },
      { text: "STATUS:Generating.. (8s · ↑ 2.1k tokens · thought for 3s)", delay: 150, instant: true },
      { text: "", delay: 300 },
      { text: "Inspecting StorageBackend trait and implementations...", delay: 350, instant: true },
      { text: "Adding exponential backoff to fast_slow_store.rs...", delay: 350, instant: true },
      { text: "  - Max retries: 3", delay: 200, instant: true },
      { text: "  - Backoff: 100ms → 400ms → 1600ms", delay: 200, instant: true },
      { text: "", delay: 400 },
      { text: "Running tests: bazel test //nativelink-store/...", delay: 300, instant: true },
      { text: "", delay: 500 },
      { text: "✓ All 32 tests passed", delay: 300, instant: true },
      { text: "✓ Changes committed to feature/storage-retry", delay: 250, instant: true },
      { text: "", delay: 200 },
      { text: "(Total: 18s · ↑ 3.4k tokens · ↓ 1.2k tokens)", delay: 300, instant: true },
      { text: "Ready for review", delay: 300, instant: true },
    ],
  },
  {
    name: "Config Update",
    lines: [
      { text: "> Enable S3 caching with 7-day TTL", delay: 0, instant: true },
      { text: "", delay: 400 },
      { text: "Using /nativelink-config-protocol...", delay: 300, instant: true },
      { text: "", delay: 300 },
      { text: "STATUS:Generating.. (2s · ↑ 520 tokens · thought for 1s)", delay: 150, instant: true },
      { text: "STATUS:Generating.. (4s · ↑ 1.1k tokens · thought for 2s)", delay: 150, instant: true },
      { text: "STATUS:Generating.. (6s · ↑ 1.8k tokens · thought for 2s)", delay: 150, instant: true },
      { text: "", delay: 300 },
      { text: "Updating config schema and examples...", delay: 350, instant: true },
      { text: "  + S3Store backend option", delay: 250, instant: true },
      { text: "  + Default TTL: 604800s (7 days)", delay: 250, instant: true },
      { text: "  ✓ Backward compatible", delay: 300, instant: true },
      { text: "", delay: 400 },
      { text: "Running validation: bazel test //nativelink-config/...", delay: 300, instant: true },
      { text: "", delay: 500 },
      { text: "✓ All 18 tests passed", delay: 300, instant: true },
      { text: "✓ Example configs load successfully", delay: 250, instant: true },
      { text: "", delay: 200 },
      { text: "(Total: 14s · ↑ 2.9k tokens · ↓ 980 tokens)", delay: 300, instant: true },
      { text: "Changes ready to deploy", delay: 300, instant: true },
    ],
  },
  {
    name: "Debug Worker",
    lines: [
      { text: "> Debug LLVM build timeout on worker-us-east-1a-003", delay: 0, instant: true },
      { text: "", delay: 400 },
      { text: "Using /nativelink-lre-debug...", delay: 300, instant: true },
      { text: "", delay: 300 },
      { text: "STATUS:Generating.. (3s · ↑ 650 tokens · thought for 2s)", delay: 150, instant: true },
      { text: "STATUS:Generating.. (6s · ↑ 1.3k tokens · thought for 3s)", delay: 150, instant: true },
      { text: "STATUS:Generating.. (9s · ↑ 1.9k tokens · thought for 4s)", delay: 150, instant: true },
      { text: "STATUS:Generating.. (11s · ↑ 2.5k tokens · thought for 5s)", delay: 150, instant: true },
      { text: "", delay: 300 },
      { text: "Checking server status and collecting logs...", delay: 350, instant: true },
      { text: "  Server: 127.0.0.1:50051 ✓", delay: 250, instant: true },
      { text: "  Worker: worker-us-east-1a-003", delay: 250, instant: true },
      { text: "  Action: compile_llvm_target (timeout after 900s)", delay: 300, instant: true },
      { text: "", delay: 400 },
      { text: "Classifying failure across subsystems...", delay: 350, instant: true },
      { text: "  Storage (CAS/AC): ✓", delay: 250, instant: true },
      { text: "  Scheduling: ✓", delay: 250, instant: true },
      { text: "  Execution: Issue detected", delay: 300, instant: true },
      { text: "", delay: 400 },
      { text: "Root cause:", delay: 250, instant: true },
      { text: "  Worker timeout (900s) < compile time (1200s)", delay: 350, instant: true },
      { text: "", delay: 400 },
      { text: "Recommendation:", delay: 250, instant: true },
      { text: "  Increase timeout to 1800s", delay: 250, instant: true },
      { text: "  File: nativelink-config/examples/worker.json5", delay: 300, instant: true },
      { text: "", delay: 200 },
      { text: "(Total: 22s · ↑ 4.1k tokens · ↓ 1.5k tokens)", delay: 300, instant: true },
    ],
  },
];
