export interface TerminalLine {
  text: string;
  delay?: number;
  instant?: boolean;
}

export interface TerminalTab {
  name: string;
  lines: TerminalLine[];
}

export const terminalTabs: TerminalTab[] = [
  {
    name: "Quick Start",
    lines: [
      { text: "curl -O https://raw.githubusercontent.com/TraceMachina/nativelink/v1.0.0/nativelink-config/examples/basic_cas.json5", delay: 0, instant: true },
      { text: "  % Total    % Received  Time", delay: 200, instant: true },
      { text: "100  2841  100  2841    0:00:01", delay: 50, instant: true },
      { text: "", delay: 300 },
      { text: "docker run -v $(pwd)/basic_cas.json:/config -p 50051:50051 ghcr.io/tracemachina/nativelink:v1.0.0 config", delay: 200, instant: true },
      { text: "", delay: 400 },
      { text: "Unable to find image locally", delay: 200, instant: true },
      { text: "v1.0.0: Pulling from tracemachina/nativelink", delay: 100, instant: true },
      { text: "a1d0c7532777: Downloading [=>              ] 15%", delay: 120, instant: true },
      { text: "a1d0c7532777: Downloading [=======>        ] 45%", delay: 120, instant: true },
      { text: "a1d0c7532777: Downloading [==============> ] 75%", delay: 120, instant: true },
      { text: "a1d0c7532777: Downloading [================] 100%", delay: 120, instant: true },
      { text: "a1d0c7532777: Pull complete", delay: 200, instant: true },
      { text: "7f9a694b6f8c: Downloading [====>           ] 25%", delay: 120, instant: true },
      { text: "7f9a694b6f8c: Downloading [=========>      ] 60%", delay: 120, instant: true },
      { text: "7f9a694b6f8c: Downloading [==============> ] 90%", delay: 120, instant: true },
      { text: "7f9a694b6f8c: Downloading [================] 100%", delay: 120, instant: true },
      { text: "7f9a694b6f8c: Pull complete", delay: 200, instant: true },
      { text: "Status: Downloaded newer image", delay: 200, instant: true },
      { text: "", delay: 400 },
      { text: "INFO nativelink::config: Loading config from /config", delay: 200, instant: true },
      { text: "INFO nativelink::cas_server: CAS server listening on 0.0.0.0:50051", delay: 150, instant: true },
      { text: "INFO nativelink::scheduler: Scheduler initialized", delay: 150, instant: true },
      { text: "✓ NativeLink ready to serve builds", delay: 300, instant: true },
    ],
  },
  {
    name: "AI Development",
    lines: [
      { text: "claude \"Add retry logic to storage layer\"", delay: 0, instant: true },
      { text: "", delay: 300 },
      { text: "Using /nativelink-rust-change skill...", delay: 400, instant: true },
      { text: "", delay: 500 },
      { text: "✓ Inspected trait: StorageBackend", delay: 300, instant: true },
      { text: "✓ Reading: nativelink-store/src/fast_slow_store.rs", delay: 250, instant: true },
      { text: "✓ Updated retry mechanism with exponential backoff", delay: 300, instant: true },
      { text: "  - Max retries: 3", delay: 150, instant: true },
      { text: "  - Backoff: 100ms → 400ms → 1600ms", delay: 150, instant: true },
      { text: "", delay: 400 },
      { text: "Running tests...", delay: 200, instant: true },
      { text: "bazel test //nativelink-store/...", delay: 250, instant: true },
      { text: "  [32 / 32] tests passed", delay: 400, instant: true },
      { text: "", delay: 300 },
      { text: "✓ Changes committed to feature/storage-retry", delay: 200, instant: true },
      { text: "Ready for review", delay: 400, instant: true },
    ],
  },
  {
    name: "Config Update",
    lines: [
      { text: "claude \"Enable S3 caching with 7-day TTL\"", delay: 0, instant: true },
      { text: "", delay: 300 },
      { text: "Using /nativelink-config-protocol skill...", delay: 400, instant: true },
      { text: "", delay: 500 },
      { text: "Identifying scope: config struct change", delay: 300, instant: true },
      { text: "", delay: 300 },
      { text: "Reading configuration files...", delay: 250, instant: true },
      { text: "  nativelink-config/examples/basic_cas.json5", delay: 200, instant: true },
      { text: "  nativelink-config/src/stores.rs", delay: 200, instant: true },
      { text: "", delay: 300 },
      { text: "Applying changes with backward compatibility:", delay: 300, instant: true },
      { text: "  + Added S3Store backend option", delay: 200, instant: true },
      { text: "  + Default TTL: 604800s (7 days)", delay: 200, instant: true },
      { text: "  ✓ Existing configs continue to load", delay: 250, instant: true },
      { text: "", delay: 400 },
      { text: "Running validation tests...", delay: 300, instant: true },
      { text: "bazel test //nativelink-config/...", delay: 250, instant: true },
      { text: "  [18 / 18] tests passed", delay: 400, instant: true },
      { text: "", delay: 300 },
      { text: "✓ Config schema validated", delay: 250, instant: true },
      { text: "✓ Example configs load successfully", delay: 250, instant: true },
      { text: "✓ Error messages verified", delay: 250, instant: true },
      { text: "", delay: 400 },
      { text: "Changes ready to deploy", delay: 300, instant: true },
    ],
  },
  {
    name: "Debug Worker",
    lines: [
      { text: "claude \"Debug LLVM build timeout on worker-us-east-1a-003\"", delay: 0, instant: true },
      { text: "", delay: 300 },
      { text: "Using /nativelink-lre-debug skill...", delay: 400, instant: true },
      { text: "", delay: 500 },
      { text: "Checking NativeLink server status...", delay: 300, instant: true },
      { text: "  ✓ Server running on 127.0.0.1:50051", delay: 250, instant: true },
      { text: "  ✓ Ports uncontested", delay: 200, instant: true },
      { text: "", delay: 300 },
      { text: "Collecting diagnostic logs...", delay: 300, instant: true },
      { text: "  Worker: worker-us-east-1a-003", delay: 200, instant: true },
      { text: "  Action: compile_llvm_target", delay: 200, instant: true },
      { text: "  Exit: timeout after 900s", delay: 200, instant: true },
      { text: "", delay: 400 },
      { text: "Classifying failure type...", delay: 300, instant: true },
      { text: "  Storage (CAS/AC): ✓ OK", delay: 200, instant: true },
      { text: "  Scheduling (worker matching): ✓ OK", delay: 200, instant: true },
      { text: "  Execution: Issue detected", delay: 200, instant: true },
      { text: "", delay: 400 },
      { text: "Root cause identified:", delay: 300, instant: true },
      { text: "  Worker timeout (900s) < actual compile time (1200s)", delay: 300, instant: true },
      { text: "", delay: 400 },
      { text: "Recommendation:", delay: 300, instant: true },
      { text: "  Increase worker timeout to 1800s", delay: 250, instant: true },
      { text: "  File: nativelink-config/examples/worker.json5", delay: 250, instant: true },
    ],
  },
];
